export const EchoNameEnum = {
  CAPITANEUS: "榮光節使",
  DRAGON_OF_DIRGE: "嘆息古龍",
  HECATE: "赫卡忒",
  LIONESS_OF_GLORY: "榮耀獅像",
  LORELEI: "羅蕾萊",
  NIGHTMARE_CROWNLESS: "夢魘·無冠者",
  NIGHTMARE_FEILIAN_BERINGAL: "夢魘·飛廉之猩",
  NIGHTMARE_IMPERMANENCE_HERON: "夢魘·無常凶鷺",
  NIGHTMARE_INFERNO_RIDER: "夢魘·燎照之騎",
  NIGHTMARE_MOURNING_AIX: "夢魘·哀聲鷙",
  NIGHTMARE_TEMPEST_MEPHIS: "夢魘·朔雷之鱗",
  NIGHTMARE_THUNDERING_MEPHIS: "夢魘·雲閃之鱗",
  NIGHTMARE_HECATE: "夢魘·赫卡忒",
  NIGHTMARE_KELPIE: "夢魘·凱爾匹",
  REMINISCENCE_FENRICO: "共鳴迴響·芬萊克",
  REMINISCENCE_FLEURDELYS: "共鳴迴響·芙露德莉斯",
  SENTRY_CONSTRUCT: "異構武裝",
} as const;
