/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Doc: typeof import('./components/Doc.vue')['default']
    DocHeaders: typeof import('./components/DocHeaders.vue')['default']
    Explorer: typeof import('./components/Explorer.vue')['default']
    Markdown: typeof import('./components/Markdown.vue')['default']
    ResonatorInfo: typeof import('./components/ResonatorInfo.vue')['default']
    ResonatorTier: typeof import('./components/ResonatorTier.vue')['default']
    Rotation: typeof import('./components/Rotation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowAutoFillEcho: typeof import('./components/RowAutoFillEcho.vue')['default']
    RowBuffResult: typeof import('./components/RowBuffResult.vue')['default']
    RowDetailedDamage: typeof import('./components/RowDetailedDamage.vue')['default']
    RowDetailedDamageNumber: typeof import('./components/RowDetailedDamageNumber.vue')['default']
    RowDetailedDamageNumbers: typeof import('./components/RowDetailedDamageNumbers.vue')['default']
    RowEcho: typeof import('./components/RowEcho.vue')['default']
    RowEchoResult: typeof import('./components/RowEchoResult.vue')['default']
    RowManualBuff: typeof import('./components/RowManualBuff.vue')['default']
    RowMonster: typeof import('./components/RowMonster.vue')['default']
    RowMonsterResult: typeof import('./components/RowMonsterResult.vue')['default']
    RowResonator: typeof import('./components/RowResonator.vue')['default']
    RowResonatorResult: typeof import('./components/RowResonatorResult.vue')['default']
    RowWeapon: typeof import('./components/RowWeapon.vue')['default']
    RowWeaponResult: typeof import('./components/RowWeaponResult.vue')['default']
    TeamTier: typeof import('./components/TeamTier.vue')['default']
    TemplateAutoFillEcho: typeof import('./components/TemplateAutoFillEcho.vue')['default']
    TemplateBasicInfo: typeof import('./components/TemplateBasicInfo.vue')['default']
    TemplateEcho: typeof import('./components/TemplateEcho.vue')['default']
    TemplateResonator: typeof import('./components/TemplateResonator.vue')['default']
    TemplateRotation: typeof import('./components/TemplateRotation.vue')['default']
  }
}
