/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Doc: typeof import('./components/Doc.vue')['default']
    DocHeaders: typeof import('./components/DocHeaders.vue')['default']
    Explorer: typeof import('./components/Explorer.vue')['default']
    Markdown: typeof import('./components/Markdown.vue')['default']
    ResonatorInfo: typeof import('./components/ResonatorInfo.vue')['default']
    ResonatorTier: typeof import('./components/ResonatorTier.vue')['default']
    Rotation: typeof import('./components/Rotation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowAutoFillEcho: typeof import('./components/RowAutoFillEcho.vue')['default']
    RowEcho: typeof import('./components/RowEcho.vue')['default']
    RowEchoResult: typeof import('./components/RowEchoResult.vue')['default']
    RowResonator: typeof import('./components/RowResonator.vue')['default']
    RowResonatorResult: typeof import('./components/RowResonatorResult.vue')['default']
    RowWeapon: typeof import('./components/RowWeapon.vue')['default']
    TeamTier: typeof import('./components/TeamTier.vue')['default']
  }
}
